package es.zurixconsulting.fichas_a4.persistencia.pojos;
// Generated 04-feb-2013 16:38:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clasificacion1 generated by hbm2java
 */
@Entity
@Table(name="CLASIFICACION1"
    ,schema="FTR"
)
public class Clasificacion1  implements java.io.Serializable {


     private String id;
     private String descripcion;

    public Clasificacion1() {
    }

	
    public Clasificacion1(String id) {
        this.id = id;
    }
    public Clasificacion1(String id, String descripcion) {
       this.id = id;
       this.descripcion = descripcion;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, length=2)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    @Column(name="DESCRIPCION", length=100)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Override
    public String toString() {
        return this.id+" - "+this.descripcion;
    }


    

}


