package es.zurixconsulting.fichas_a4.persistencia.pojos;
// Generated 06-feb-2013 17:57:27 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Fichatecnica generated by hbm2java
 */
@Entity
@Table(name="FICHATECNICA"
    ,schema="FTR"
)
public class Fichatecnica  implements java.io.Serializable {


     private String ncertificado;
     private String nbastidor;
     private Date fechatarjeta;
     private String tipo;
     private Integer fabricante;
     private String d1marca;
     private String d2tipo;
     private String d2variante;
     private String d2version;
     private String d3denom;
     private String khomol;
     private String khomolc;
     private String rdc;
     private String a1;
     private String a2;
     private String ciitv;
     private Integer d6;
     private Integer s1;
     private String k;
     private String z;
     private String observaciones;
     private String opciones;
     private String cv;
     private Integer lne;
     private Integer lnr;
     private Integer l0;
     private Integer l1ne;
     private Integer l1pe;
     private String l2;
     private String g;
     private String f1;
     private String f11;
     private String f15;
     private String o14;
     private String o13;
     private String o12;
     private String o11;
     private String o1;
     private String f3;
     private String f31;
     private String m4;
     private String f4;
     private String f5;
     private String f6;
     private String f7;
     private String f71;
     private String f8;
     private String p51;
     private String p5;
     private String p11;
     private String p1;
     private String p2;
     private String p21;
     private String v9;
     private String v1;
     private String v2;
     private String v7;
     private String jcateg;
     private String j1;
     private String p3;
     private String r;
     private String cl1;
     private String cl2;
     private String f2;
     private String f21;

    public Fichatecnica() {
    }

	
    public Fichatecnica(String ncertificado) {
        this.ncertificado = ncertificado;
    }
    public Fichatecnica(String ncertificado, String nbastidor, Date fechatarjeta, String tipo, Integer fabricante, String d1marca, String d2tipo, String d2variante, String d2version, String d3denom, String khomol, String khomolc, String rdc, String a1, String a2, String ciitv, Integer d6, Integer s1, String k, String z, String observaciones, String opciones, String cv, Integer lne, Integer lnr, Integer l0, Integer l1ne, Integer l1pe, String l2, String g, String f1, String f11, String f15, String o14, String o13, String o12, String o11, String o1, String f3, String f31, String m4, String f4, String f5, String f6, String f7, String f71, String f8, String p51, String p5, String p11, String p1, String p2, String p21, String v9, String v1, String v2, String v7, String jcateg, String j1, String p3, String r, String cl1, String cl2, String f2, String f21) {
       this.ncertificado = ncertificado;
       this.nbastidor = nbastidor;
       this.fechatarjeta = fechatarjeta;
       this.tipo = tipo;
       this.fabricante = fabricante;
       this.d1marca = d1marca;
       this.d2tipo = d2tipo;
       this.d2variante = d2variante;
       this.d2version = d2version;
       this.d3denom = d3denom;
       this.khomol = khomol;
       this.khomolc = khomolc;
       this.rdc = rdc;
       this.a1 = a1;
       this.a2 = a2;
       this.ciitv = ciitv;
       this.d6 = d6;
       this.s1 = s1;
       this.k = k;
       this.z = z;
       this.observaciones = observaciones;
       this.opciones = opciones;
       this.cv = cv;
       this.lne = lne;
       this.lnr = lnr;
       this.l0 = l0;
       this.l1ne = l1ne;
       this.l1pe = l1pe;
       this.l2 = l2;
       this.g = g;
       this.f1 = f1;
       this.f11 = f11;
       this.f15 = f15;
       this.o14 = o14;
       this.o13 = o13;
       this.o12 = o12;
       this.o11 = o11;
       this.o1 = o1;
       this.f3 = f3;
       this.f31 = f31;
       this.m4 = m4;
       this.f4 = f4;
       this.f5 = f5;
       this.f6 = f6;
       this.f7 = f7;
       this.f71 = f71;
       this.f8 = f8;
       this.p51 = p51;
       this.p5 = p5;
       this.p11 = p11;
       this.p1 = p1;
       this.p2 = p2;
       this.p21 = p21;
       this.v9 = v9;
       this.v1 = v1;
       this.v2 = v2;
       this.v7 = v7;
       this.jcateg = jcateg;
       this.j1 = j1;
       this.p3 = p3;
       this.r = r;
       this.cl1 = cl1;
       this.cl2 = cl2;
       this.f2 = f2;
       this.f21 = f21;
    }
   
     @Id 
    
    @Column(name="NCERTIFICADO", unique=true, nullable=false, length=7)
    public String getNcertificado() {
        return this.ncertificado;
    }
    
    public void setNcertificado(String ncertificado) {
        this.ncertificado = ncertificado;
    }
    
    @Column(name="NBASTIDOR", length=20)
    public String getNbastidor() {
        return this.nbastidor;
    }
    
    public void setNbastidor(String nbastidor) {
        this.nbastidor = nbastidor;
    }
    @Temporal(TemporalType.DATE)
    @Column(name="FECHATARJETA", length=10)
    public Date getFechatarjeta() {
        return this.fechatarjeta;
    }
    
    public void setFechatarjeta(Date fechatarjeta) {
        this.fechatarjeta = fechatarjeta;
    }
    
    @Column(name="TIPO", length=1)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    
    @Column(name="FABRICANTE", precision=5, scale=0)
    public Integer getFabricante() {
        return this.fabricante;
    }
    
    public void setFabricante(Integer fabricante) {
        this.fabricante = fabricante;
    }
    
    @Column(name="D1MARCA", length=50)
    public String getD1marca() {
        return this.d1marca;
    }
    
    public void setD1marca(String d1marca) {
        this.d1marca = d1marca;
    }
    
    @Column(name="D2TIPO", length=50)
    public String getD2tipo() {
        return this.d2tipo;
    }
    
    public void setD2tipo(String d2tipo) {
        this.d2tipo = d2tipo;
    }
    
    @Column(name="D2VARIANTE", length=50)
    public String getD2variante() {
        return this.d2variante;
    }
    
    public void setD2variante(String d2variante) {
        this.d2variante = d2variante;
    }
    
    @Column(name="D2VERSION", length=50)
    public String getD2version() {
        return this.d2version;
    }
    
    public void setD2version(String d2version) {
        this.d2version = d2version;
    }
    
    @Column(name="D3DENOM", length=50)
    public String getD3denom() {
        return this.d3denom;
    }
    
    public void setD3denom(String d3denom) {
        this.d3denom = d3denom;
    }
    
    @Column(name="KHOMOL", length=50)
    public String getKhomol() {
        return this.khomol;
    }
    
    public void setKhomol(String khomol) {
        this.khomol = khomol;
    }
    
    @Column(name="KHOMOLC", length=50)
    public String getKhomolc() {
        return this.khomolc;
    }
    
    public void setKhomolc(String khomolc) {
        this.khomolc = khomolc;
    }
    
    @Column(name="RDC", length=50)
    public String getRdc() {
        return this.rdc;
    }
    
    public void setRdc(String rdc) {
        this.rdc = rdc;
    }
    
    @Column(name="A1", length=50)
    public String getA1() {
        return this.a1;
    }
    
    public void setA1(String a1) {
        this.a1 = a1;
    }
    
    @Column(name="A2", length=50)
    public String getA2() {
        return this.a2;
    }
    
    public void setA2(String a2) {
        this.a2 = a2;
    }
    
    @Column(name="CIITV", length=50)
    public String getCiitv() {
        return this.ciitv;
    }
    
    public void setCiitv(String ciitv) {
        this.ciitv = ciitv;
    }
    
    @Column(name="D6", precision=5, scale=0)
    public Integer getD6() {
        return this.d6;
    }
    
    public void setD6(Integer d6) {
        this.d6 = d6;
    }
    
    @Column(name="S1", precision=5, scale=0)
    public Integer getS1() {
        return this.s1;
    }
    
    public void setS1(Integer s1) {
        this.s1 = s1;
    }
    
    @Column(name="K", length=50)
    public String getK() {
        return this.k;
    }
    
    public void setK(String k) {
        this.k = k;
    }
    
    @Column(name="Z", length=50)
    public String getZ() {
        return this.z;
    }
    
    public void setZ(String z) {
        this.z = z;
    }
    
    @Column(name="OBSERVACIONES")
    public String getObservaciones() {
        return this.observaciones;
    }
    
    public void setObservaciones(String observaciones) {
        this.observaciones = observaciones;
    }
    
    @Column(name="OPCIONES")
    public String getOpciones() {
        return this.opciones;
    }
    
    public void setOpciones(String opciones) {
        this.opciones = opciones;
    }
    
    @Column(name="CV", length=50)
    public String getCv() {
        return this.cv;
    }
    
    public void setCv(String cv) {
        this.cv = cv;
    }
    
    @Column(name="LNE", precision=5, scale=0)
    public Integer getLne() {
        return this.lne;
    }
    
    public void setLne(Integer lne) {
        this.lne = lne;
    }
    
    @Column(name="LNR", precision=5, scale=0)
    public Integer getLnr() {
        return this.lnr;
    }
    
    public void setLnr(Integer lnr) {
        this.lnr = lnr;
    }
    
    @Column(name="L0", precision=5, scale=0)
    public Integer getL0() {
        return this.l0;
    }
    
    public void setL0(Integer l0) {
        this.l0 = l0;
    }
    
    @Column(name="L1NE", precision=5, scale=0)
    public Integer getL1ne() {
        return this.l1ne;
    }
    
    public void setL1ne(Integer l1ne) {
        this.l1ne = l1ne;
    }
    
    @Column(name="L1PE", precision=5, scale=0)
    public Integer getL1pe() {
        return this.l1pe;
    }
    
    public void setL1pe(Integer l1pe) {
        this.l1pe = l1pe;
    }
    
    @Column(name="L2", length=50)
    public String getL2() {
        return this.l2;
    }
    
    public void setL2(String l2) {
        this.l2 = l2;
    }
    
    @Column(name="G", length=50)
    public String getG() {
        return this.g;
    }
    
    public void setG(String g) {
        this.g = g;
    }
    
    @Column(name="F1", length=50)
    public String getF1() {
        return this.f1;
    }
    
    public void setF1(String f1) {
        this.f1 = f1;
    }
    
    @Column(name="F11", length=50)
    public String getF11() {
        return this.f11;
    }
    
    public void setF11(String f11) {
        this.f11 = f11;
    }
    
    @Column(name="F15", length=50)
    public String getF15() {
        return this.f15;
    }
    
    public void setF15(String f15) {
        this.f15 = f15;
    }
    
    @Column(name="O14", length=50)
    public String getO14() {
        return this.o14;
    }
    
    public void setO14(String o14) {
        this.o14 = o14;
    }
    
    @Column(name="O13", length=50)
    public String getO13() {
        return this.o13;
    }
    
    public void setO13(String o13) {
        this.o13 = o13;
    }
    
    @Column(name="O12", length=50)
    public String getO12() {
        return this.o12;
    }
    
    public void setO12(String o12) {
        this.o12 = o12;
    }
    
    @Column(name="O11", length=50)
    public String getO11() {
        return this.o11;
    }
    
    public void setO11(String o11) {
        this.o11 = o11;
    }
    
    @Column(name="O1", length=50)
    public String getO1() {
        return this.o1;
    }
    
    public void setO1(String o1) {
        this.o1 = o1;
    }
    
    @Column(name="F3", length=50)
    public String getF3() {
        return this.f3;
    }
    
    public void setF3(String f3) {
        this.f3 = f3;
    }
    
    @Column(name="F31", length=50)
    public String getF31() {
        return this.f31;
    }
    
    public void setF31(String f31) {
        this.f31 = f31;
    }
    
    @Column(name="M4", length=50)
    public String getM4() {
        return this.m4;
    }
    
    public void setM4(String m4) {
        this.m4 = m4;
    }
    
    @Column(name="F4", length=50)
    public String getF4() {
        return this.f4;
    }
    
    public void setF4(String f4) {
        this.f4 = f4;
    }
    
    @Column(name="F5", length=50)
    public String getF5() {
        return this.f5;
    }
    
    public void setF5(String f5) {
        this.f5 = f5;
    }
    
    @Column(name="F6", length=50)
    public String getF6() {
        return this.f6;
    }
    
    public void setF6(String f6) {
        this.f6 = f6;
    }
    
    @Column(name="F7", length=50)
    public String getF7() {
        return this.f7;
    }
    
    public void setF7(String f7) {
        this.f7 = f7;
    }
    
    @Column(name="F71", length=50)
    public String getF71() {
        return this.f71;
    }
    
    public void setF71(String f71) {
        this.f71 = f71;
    }
    
    @Column(name="F8", length=50)
    public String getF8() {
        return this.f8;
    }
    
    public void setF8(String f8) {
        this.f8 = f8;
    }
    
    @Column(name="P51", length=50)
    public String getP51() {
        return this.p51;
    }
    
    public void setP51(String p51) {
        this.p51 = p51;
    }
    
    @Column(name="P5", length=50)
    public String getP5() {
        return this.p5;
    }
    
    public void setP5(String p5) {
        this.p5 = p5;
    }
    
    @Column(name="P11", length=50)
    public String getP11() {
        return this.p11;
    }
    
    public void setP11(String p11) {
        this.p11 = p11;
    }
    
    @Column(name="P1", length=50)
    public String getP1() {
        return this.p1;
    }
    
    public void setP1(String p1) {
        this.p1 = p1;
    }
    
    @Column(name="P2", length=50)
    public String getP2() {
        return this.p2;
    }
    
    public void setP2(String p2) {
        this.p2 = p2;
    }
    
    @Column(name="P21", length=50)
    public String getP21() {
        return this.p21;
    }
    
    public void setP21(String p21) {
        this.p21 = p21;
    }
    
    @Column(name="V9", length=50)
    public String getV9() {
        return this.v9;
    }
    
    public void setV9(String v9) {
        this.v9 = v9;
    }
    
    @Column(name="V1", length=50)
    public String getV1() {
        return this.v1;
    }
    
    public void setV1(String v1) {
        this.v1 = v1;
    }
    
    @Column(name="V2", length=50)
    public String getV2() {
        return this.v2;
    }
    
    public void setV2(String v2) {
        this.v2 = v2;
    }
    
    @Column(name="V7", length=50)
    public String getV7() {
        return this.v7;
    }
    
    public void setV7(String v7) {
        this.v7 = v7;
    }
    
    @Column(name="JCATEG", length=3)
    public String getJcateg() {
        return this.jcateg;
    }
    
    public void setJcateg(String jcateg) {
        this.jcateg = jcateg;
    }
    
    @Column(name="J1", length=2)
    public String getJ1() {
        return this.j1;
    }
    
    public void setJ1(String j1) {
        this.j1 = j1;
    }
    
    @Column(name="P3", length=3)
    public String getP3() {
        return this.p3;
    }
    
    public void setP3(String p3) {
        this.p3 = p3;
    }
    
    @Column(name="R", length=2)
    public String getR() {
        return this.r;
    }
    
    public void setR(String r) {
        this.r = r;
    }
    
    @Column(name="CL1", length=2)
    public String getCl1() {
        return this.cl1;
    }
    
    public void setCl1(String cl1) {
        this.cl1 = cl1;
    }
    
    @Column(name="CL2", length=2)
    public String getCl2() {
        return this.cl2;
    }
    
    public void setCl2(String cl2) {
        this.cl2 = cl2;
    }
    
    @Column(name="F2", length=10)
    public String getF2() {
        return this.f2;
    }
    
    public void setF2(String f2) {
        this.f2 = f2;
    }
    
    @Column(name="F21", length=10)
    public String getF21() {
        return this.f21;
    }
    
    public void setF21(String f21) {
        this.f21 = f21;
    }




}


