package es.zurixconsulting.fichas_a4.persistencia.pojos;
// Generated 04-feb-2013 16:38:36 by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Procedencia generated by hbm2java
 */
@Entity
@Table(name="PROCEDENCIA"
    ,schema="FTR"
)
public class Procedencia  implements java.io.Serializable {


     private int id;
     private String descricpion;

    public Procedencia() {
    }

	
    public Procedencia(int id) {
        this.id = id;
    }
    public Procedencia(int id, String descricpion) {
       this.id = id;
       this.descricpion = descricpion;
    }
   
     @Id 
    
    @Column(name="ID", unique=true, nullable=false, precision=5, scale=0)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="DESCRICPION", length=100)
    public String getDescricpion() {
        return this.descricpion;
    }
    
    public void setDescricpion(String descricpion) {
        this.descricpion = descricpion;
    }


@Override
    public String toString() {
        return this.descricpion;
    }

}


