/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package es.zurixconsulting.fichas_a4;


import es.zurixconsulting.fichas_a4.persistencia.models.FichasModel;
import es.zurixconsulting.fichas_a4.persistencia.pojos.Fichatecnica;
import es.zurixconsulting.fichas_a4.ImpresionFicha;
import javax.swing.ImageIcon;

/**
 *
 * @author aperalta
 */
public class MainUI extends javax.swing.JFrame {

   
    public static FichasModel bbdd_Fichas = new FichasModel();
    
    /**
     * Creates new form MainUI
     */
    public MainUI() {
        
        initComponents();
         this.setIconImage(new ImageIcon(getClass().getResource("/es/zurixconsulting/fichas_a4/LogoA4.png")).getImage());
        this.setTitle("-FICHAS A4- \t\t");
        
        
        
        String[] cab = {"Fecha", "Nº Certificado","Bastidor"};
        String[] props = {"fechatarjeta", "ncertificado","nbastidor"};
        this.jTableArrayList2.setCaps(props, cab);
        this.jTableArrayList2.setList(bbdd_Fichas.getLista());
        
        this.jTableArrayList3.setCaps(props, cab);
        this.jTableArrayList3.setList(bbdd_Fichas.getPlantillas());
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableArrayList2 = new win8.swing.MetroTableUI();
        jLabel2 = new javax.swing.JLabel();
        jMetroButton3 = new es.zurixconsulting.fichas_a4.JMetroButton();
        jMetroButton4 = new es.zurixconsulting.fichas_a4.JMetroButton();
        jMetroButton5 = new es.zurixconsulting.fichas_a4.JMetroButton();
        jMetroButton6 = new es.zurixconsulting.fichas_a4.JMetroButton();
        jMetroButton7 = new es.zurixconsulting.fichas_a4.JMetroButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableArrayList3 = new win8.swing.MetroTableUI();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(865, 508));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Identificador");

        jTextField2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(0, 153, 255));
        jTextField2.setText("Busqueda rapida de fichas");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 255), 3));
        jTextField2.setMargin(new java.awt.Insets(20, 20, 20, 20));
        jTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField2FocusGained(evt);
            }
        });

        jScrollPane2.setBorder(null);

        jTableArrayList2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableArrayList2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTableArrayList2.setGridColor(new java.awt.Color(255, 255, 255));
        jTableArrayList2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArrayList2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableArrayList2);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("- FICHAS A4 -");

        jMetroButton3.setBackground(new java.awt.Color(0, 153, 255));
        jMetroButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jMetroButton3.setForeground(new java.awt.Color(255, 255, 255));
        jMetroButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/zurixconsulting/fichas_a4/numerosMetro/add.png"))); // NOI18N
        jMetroButton3.setText("NUEVA FICHA");
        jMetroButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMetroButton3ActionPerformed(evt);
            }
        });

        jMetroButton4.setBackground(new java.awt.Color(0, 153, 255));
        jMetroButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jMetroButton4.setForeground(new java.awt.Color(255, 255, 255));
        jMetroButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/zurixconsulting/fichas_a4/numerosMetro/edit.png"))); // NOI18N
        jMetroButton4.setText("EDITAR FICHA");
        jMetroButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMetroButton4ActionPerformed(evt);
            }
        });

        jMetroButton5.setBackground(new java.awt.Color(51, 153, 255));
        jMetroButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jMetroButton5.setForeground(new java.awt.Color(255, 255, 255));
        jMetroButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/zurixconsulting/fichas_a4/numerosMetro/delete.png"))); // NOI18N
        jMetroButton5.setText("ELIMINAR FICHA");
        jMetroButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMetroButton5ActionPerformed(evt);
            }
        });

        jMetroButton6.setBackground(new java.awt.Color(0, 153, 255));
        jMetroButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jMetroButton6.setForeground(new java.awt.Color(255, 255, 255));
        jMetroButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/zurixconsulting/fichas_a4/numerosMetro/printer.png"))); // NOI18N
        jMetroButton6.setText("IMPRIMIR FICHA");
        jMetroButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMetroButton6ActionPerformed(evt);
            }
        });

        jMetroButton7.setBackground(new java.awt.Color(51, 153, 255));
        jMetroButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jMetroButton7.setForeground(new java.awt.Color(255, 255, 255));
        jMetroButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/es/zurixconsulting/fichas_a4/numerosMetro/search.png"))); // NOI18N
        jMetroButton7.setText("BUSCAR");
        jMetroButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMetroButton7ActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(null);

        jTableArrayList3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableArrayList3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTableArrayList3.setGridColor(new java.awt.Color(255, 255, 255));
        jTableArrayList3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableArrayList3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableArrayList3);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PLANTILLAS: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jMetroButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMetroButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jMetroButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jMetroButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jMetroButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 24, Short.MAX_VALUE))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(39, 39, 39))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMetroButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMetroButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMetroButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addComponent(jMetroButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jMetroButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(255, 255, 255));

        jMenu1.setBackground(new java.awt.Color(0, 153, 255));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jMenu1.setForeground(new java.awt.Color(255, 255, 255));
        jMenu1.setText("Archivo");
        jMenu1.setAutoscrolls(true);

        jMenuItem2.setBackground(new java.awt.Color(0, 153, 255));
        jMenuItem2.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem2.setText("Nueva Ficha");
        jMenuItem2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuItem1.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem1.setText("Salir");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jMenu2.setForeground(new java.awt.Color(255, 255, 255));
        jMenu2.setText("Ayuda");

        jMenuItem3.setBackground(new java.awt.Color(0, 153, 255));
        jMenuItem3.setForeground(new java.awt.Color(255, 255, 255));
        jMenuItem3.setText("Acerca de...");
        jMenuItem3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMetroButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMetroButton3ActionPerformed
        new CreacionEdidionA4(this,true);
        this.jTableArrayList2.setList(bbdd_Fichas.getLista());
        this.jTableArrayList3.setList(bbdd_Fichas.getPlantillas());
    }//GEN-LAST:event_jMetroButton3ActionPerformed

    private void jMetroButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMetroButton4ActionPerformed
        new CreacionEdidionA4((Fichatecnica)this.jTableArrayList2.getSelectElement(),this,true);
        this.jTableArrayList2.setList(bbdd_Fichas.getLista());
       this.jTableArrayList3.setList(bbdd_Fichas.getPlantillas());
    }//GEN-LAST:event_jMetroButton4ActionPerformed

    private void jMetroButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMetroButton5ActionPerformed
        MainUI.bbdd_Fichas.removeDato((Fichatecnica)this.jTableArrayList2.getSelectElement());
        this.jTableArrayList2.setList(bbdd_Fichas.getLista());
    }//GEN-LAST:event_jMetroButton5ActionPerformed

    private void jTextField2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField2FocusGained
       this.jTextField2.selectAll();
    }//GEN-LAST:event_jTextField2FocusGained

    private void jMetroButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMetroButton7ActionPerformed
        this.jTableArrayList2.setList(bbdd_Fichas.getBusqueda(this.jTextField2.getText()));
    }//GEN-LAST:event_jMetroButton7ActionPerformed

    private void jMetroButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMetroButton6ActionPerformed
      // ImpresionFicha print = new ImpresionFicha();
        
         ImpresionFicha.print((Fichatecnica)this.jTableArrayList2.getSelectElement(), this);
    }//GEN-LAST:event_jMetroButton6ActionPerformed

    private void jTableArrayList2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArrayList2MouseClicked
       if(evt.getClickCount()>=2){
            new CreacionEdidionA4((Fichatecnica)this.jTableArrayList2.getSelectElement(),this,true);
            this.jTableArrayList2.setList(bbdd_Fichas.getLista());
            this.jTableArrayList3.setList(bbdd_Fichas.getPlantillas());
       }
    }//GEN-LAST:event_jTableArrayList2MouseClicked

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new CreacionEdidionA4(this,true);
        this.jTableArrayList2.setList(bbdd_Fichas.getLista());
        this.jTableArrayList3.setList(bbdd_Fichas.getPlantillas());
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        new QuienesSomos(this, true).setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jTableArrayList3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableArrayList3MouseClicked
        if(evt.getClickCount()>=2){
            new CreacionEdidionA4((Fichatecnica)this.jTableArrayList3.getSelectElement(),this,true,true);
            this.jTableArrayList2.setList(bbdd_Fichas.getLista());
            this.jTableArrayList3.setList(bbdd_Fichas.getPlantillas());
       }
    }//GEN-LAST:event_jTableArrayList3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private es.zurixconsulting.fichas_a4.JMetroButton jMetroButton3;
    private es.zurixconsulting.fichas_a4.JMetroButton jMetroButton4;
    private es.zurixconsulting.fichas_a4.JMetroButton jMetroButton5;
    private es.zurixconsulting.fichas_a4.JMetroButton jMetroButton6;
    private es.zurixconsulting.fichas_a4.JMetroButton jMetroButton7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private es.timmp.componets.JTableArrayList jTableArrayList2;
    private es.timmp.componets.JTableArrayList jTableArrayList3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
